"""add refresh_token to github_installations

Revision ID: 821a280729a3
Revises: f60d92ee2881
Create Date: 2026-08-18 02:38:42.425294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821a280729a3'
down_revision: Union[str, Sequence[str], None] = 'f60d92ee2881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_installations', sa.Column('refresh_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_installations', 'refresh_token')
    # ### end Alembic commands ###
