"""add access_token to github_installations

Revision ID: f60d92ee2881
Revises: b7f31d3c2e09
Create Date: 2026-08-17 13:54:35.666145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60d92ee2881'
down_revision: Union[str, Sequence[str], None] = 'b7f31d3c2e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('app_users_session_token_key'), 'app_users', type_='unique')
    op.drop_index(op.f('ix_app_users_session_token'), table_name='app_users')
    op.create_index(op.f('ix_app_users_session_token'), 'app_users', ['session_token'], unique=True)
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_index(op.f('document_chunks_embedding_idx'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('github_installations', sa.Column('access_token', sa.String(length=512), nullable=True))
    op.alter_column('github_installations', 'installation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('github_installations_installation_id_key'), 'github_installations', type_='unique')
    op.create_index(op.f('ix_github_installations_installation_id'), 'github_installations', ['installation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_installations_installation_id'), table_name='github_installations')
    op.create_unique_constraint(op.f('github_installations_installation_id_key'), 'github_installations', ['installation_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('github_installations', 'installation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('github_installations', 'access_token')
    op.create_index(op.f('document_chunks_embedding_idx'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_app_users_session_token'), table_name='app_users')
    op.create_index(op.f('ix_app_users_session_token'), 'app_users', ['session_token'], unique=False)
    op.create_unique_constraint(op.f('app_users_session_token_key'), 'app_users', ['session_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
